#ifndef _SCAN_CODES_
#define _SCAN_CODES_

#include <stdint.h>
typedef uint8_t scan_code_t; 

#define SCN_CD_RESERVED0 0x00U      
#define SCN_CD_ERR_ROLL_OVER 0x01U
#define SCN_CD_POST_FAIL 0x02U 
#define SCN_CD_ERR_UNDEFINED  0x03U
#define SCN_CD_A 0x04U   
#define SCN_CD_B 0x05U
#define SCN_CD_C 0x06U
#define SCN_CD_D 0x07U
#define SCN_CD_E 0x08U
#define SCN_CD_F 0x09U
#define SCN_CD_G 0x0aU
#define SCN_CD_H 0x0bU
#define SCN_CD_I 0x0cU
#define SCN_CD_J 0x0dU
#define SCN_CD_K 0x0eU
#define SCN_CD_L 0x0fU
#define SCN_CD_M 0x10U
#define SCN_CD_N 0x11U
#define SCN_CD_O 0x12U
#define SCN_CD_P 0x13U
#define SCN_CD_Q 0x14U
#define SCN_CD_R 0x15U
#define SCN_CD_S 0x16U
#define SCN_CD_T 0x17U
#define SCN_CD_U 0x18U
#define SCN_CD_V 0x19U
#define SCN_CD_W 0x1aU
#define SCN_CD_X 0x1bU
#define SCN_CD_Y 0x1cU
#define SCN_CD_Z 0x1dU
#define SCN_CD_1 0x1eU 
#define SCN_CD_2 0x1fU 
#define SCN_CD_3 0x20U 
#define SCN_CD_4 0x21U 
#define SCN_CD_5 0x22U 
#define SCN_CD_6 0x23U 
#define SCN_CD_7 0x24U 
#define SCN_CD_8 0x25U 
#define SCN_CD_9 0x26U 
#define SCN_CD_0 0x27U 
#define SCN_CD_RET 0x28U
#define SCN_CD_ESC 0x29U
#define SCN_CD_DEL 0x2aU
#define SCN_CD_TAB 0x2bU
#define SCN_CD_SPACE 0x2cU
#define SCN_CD_DASH 0x2dU
#define SCN_CD_EQUAL 0x2eU
#define SCN_CD_R_BRACKET 0x2fU
#define SCN_CD_L_BRACKET 0x30U
#define SCN_CD_BCK_SLASH 0x31U
#define SCN_CD_NON_US_HASHTAG 0x32U
#define SCN_CD_SEMICOLON 0x33U
#define SCN_CD_APOSTROPHE 0x34U
#define SCN_CD_GRAVE_ACCENT 0x35U 
#define SCN_CD_COMMA 0x36U
#define SCN_CD_PERIOD 0x37U
#define SCN_CD_FWD_SLASH 0x38U
#define SCN_CD_CAPS_LOCK 0x39U
#define SCN_CD_F1 0x3aU
#define SCN_CD_F2 0x3bU
#define SCN_CD_F3 0x3cU
#define SCN_CD_F4 0x3dU
#define SCN_CD_F5 0x3eU
#define SCN_CD_F6 0x3fU
#define SCN_CD_F7 0x40U
#define SCN_CD_F8 0x41U
#define SCN_CD_F9 0x42U
#define SCN_CD_F10 0x43U
#define SCN_CD_F11 0x44U
#define SCN_CD_F12 0x45U
#define SCN_CD_PRINT_SCR 0x46U 
#define SCN_CD_SCRL_LCK 0x47U
#define SCN_CD_PAUSE 0x48U
#define SCN_CD_INSERT 0x49U
#define SCN_CD_HOME 0x4aU
#define SCN_CD_PG_UP 0x4bU
#define SCN_CD_DEL_FWD 0x4cU
#define SCN_CD_END 0x4dU
#define SCN_CD_PG_DWN 0x4eU
#define SCN_CD_R_ARROW 0x4fU
#define SCN_CD_L_ARROW 0x50U
#define SCN_CD_D_ARROW 0x51U
#define SCN_CD_U_ARROW 0x52U
#define SCN_CD_NUM_LOCK 0x53U
#define SCN_CD_KP_SLSH1 0x54U
#define SCN_CD_KP_ASTERISK 0x55U
#define SCN_CD_KP_DASH 0x56U
#define SCN_CD_KP_PLUS 0x57U
#define SCN_CD_KP_ENT 0x58U
#define SCN_CD_KP_1 0x59U
#define SCN_CD_KP_2 0x5aU
#define SCN_CD_KP_3 0x5bU
#define SCN_CD_KP_4 0x5cU
#define SCN_CD_KP_5 0x5dU
#define SCN_CD_KP_6 0x5eU
#define SCN_CD_KP_7 0x5fU
#define SCN_CD_KP_8 0x60U
#define SCN_CD_KP_9 0x61U
#define SCN_CD_KP_0 0x62U
#define SCN_CD_KP_PERIOD 0x63U
#define SCN_CD_NON_US_BCK_SLSH 0x64U
#define SCN_CD_APP 0x65U
#define SCN_CD_PWR 0x66U
#define SCN_CD_KP_EQUAL 0x67U
#define SCN_CD_F13 0x68U
#define SCN_CD_F14 0x69U
#define SCN_CD_F15 0x6aU
#define SCN_CD_F16 0x6bU
#define SCN_CD_F17 0x6cU
#define SCN_CD_F18 0x6dU
#define SCN_CD_F19 0x6eU
#define SCN_CD_F20 0x6fU
#define SCN_CD_F21 0x70U
#define SCN_CD_F22 0x71U
#define SCN_CD_F23 0x72U
#define SCN_CD_F24 0x73U
#define SCN_CD_EXECUTE 0x74U
#define SCN_CD_HLP 0x75U
#define SCN_CD_MENU 0x76U
#define SCN_CD_SELECT 0x77U
#define SCN_CD_STOP 0x78U
#define SCN_CD_AGAIN 0x79U
#define SCN_CD_UNDO 0x7aU
#define SCN_CD_CUT 0x7bU
#define SCN_CD_CPY 0x7cU
#define SCN_CD_PASTE 0x7dU
#define SCN_CD_FIND 0x7eU
#define SCN_CD_MUTE 0x7fU
#define SCN_CD_VOL_UP 0x80U
#define SCN_CD_VOL_DWN 0x81U
#define SCN_CD_LOCKING_CAPS_LCK 0x82U
#define SCN_CD_LOCKING_NUM_LCK 0x83U
#define SCN_CD_LOCKING_SCRL_LCK 0x84U
#define SCN_CD_KP_COMMA 0x85U
#define SCN_CD_KP_EQUAL_SIGN 0x86U
#define SCN_CD_INTERNATIONAL1 0x87U
#define SCN_CD_INTERNATIONAL2 0x88U
#define SCN_CD_INTERNATIONAL3 0x89U
#define SCN_CD_INTERNATIONAL4 0x8aU
#define SCN_CD_INTERNATIONAL5 0x8bU
#define SCN_CD_INTERNATIONAL6 0x8cU
#define SCN_CD_INTERNATIONAL7 0x8dU
#define SCN_CD_INTERNATIONAL8 0x8eU
#define SCN_CD_INTERNATIONAL9 0x8fU
#define SCN_CD_LANG1 0x90U
#define SCN_CD_LANG2 0x91U
#define SCN_CD_LANG3 0x92U
#define SCN_CD_LANG4 0x93U
#define SCN_CD_LANG5 0x94U
#define SCN_CD_LANG6 0x95U
#define SCN_CD_LANG7 0x96U
#define SCN_CD_LANG8 0x97U
#define SCN_CD_LANG9 0x98U
#define SCN_CD_ALT_ERASE 0x99U
#define SCN_CD_SYSREQ 0x9aU
#define SCN_CD_CANCEL 0x9bU
#define SCN_CD_CLR 0x9cU
#define SCN_CD_PRIOR 0x9dU
#define SCN_CD_RETURN 0x9eU
#define SCN_CD_SEPARATOR 0x9fU
#define SCN_CD_OUT 0xa0U
#define SCN_CD_OPER 0xa1U
#define SCN_CD_CLEAR_AGAIN 0xa2U
#define SCN_CD_CRSEL 0xa3U
#define SCN_CD_EXSEL 0xa4U
#define SCN_CD_RESERVED1 0xa5U
#define SCN_CD_RESERVED2 0xa6U
#define SCN_CD_RESERVED3 0xa7U
#define SCN_CD_RESERVED4 0xa8U
#define SCN_CD_RESERVED5 0xa9U
#define SCN_CD_RESERVED6 0xaaU
#define SCN_CD_RESERVED7 0xabU
#define SCN_CD_RESERVED8 0xacU
#define SCN_CD_RESERVED9 0xadU
#define SCN_CD_RESERVED10 0xaeU
#define SCN_CD_RESERVED11 0xafU
#define SCN_CD_KP_00 0xb0U
#define SCN_CD_KP_000 0xb1U
#define SCN_CD_THOUSANDS_SEPARATOR 0xb2U
#define SCN_CD_DECIMAL_SEPARATOR 0xb3U
#define SCN_CD_CURRENCY_UNIT 0xb4U
#define SCN_CD_CURRENCY_SUB_UNIT 0xb5U
#define SCN_CD_KP_L_PARENTHESIS 0xb6U
#define SCN_CD_KP_R_PARANTHESIS 0xb7U
#define SCN_CD_KP_L_BRACE 0xb8U
#define SCN_CD_KP_R_BRACE 0xb9U
#define SCN_CD_KP_TAB 0xbaU
#define SCN_CD_KP_BCKSPACE 0xbbU
#define SCN_CD_KP_A 0xbcU
#define SCN_CD_KP_B 0xbdU
#define SCN_CD_KP_C 0xbeU
#define SCN_CD_KP_D 0xbfU
#define SCN_CD_KP_E 0xc0U
#define SCN_CD_KP_F 0xc1U
#define SCN_CD_KP_XOR 0xc2U
#define SCN_CD_KP_CARET 0xc3U
#define SCN_CD_KP_PERCENT 0xc4U
#define SCN_CD_KP_LESS_THAN 0xc5U
#define SCN_CD_KP_GREATER_THAN 0xc6U
#define SCN_CD_KP_APERSAND 0xc7U
#define SCN_CD_KP_DOUBLE_AMPERSAND 0xc8U
#define SCN_CD_KP_VERT_BAR 0xc9U
#define SCN_CD_KP_DOUBLE_VERT_BAR 0xcaU
#define SCN_CD_KP_COLON 0xcbU
#define SCN_CD_KP_HASHTAG 0xccU
#define SCN_CD_KP_SPACE 0xcdU
#define SCN_CD_KP_AMPERSAT 0xceU
#define SCN_CD_KP_EXCLAMATION 0xcfU
#define SCN_CD_KP_MEM_STORE 0xd0U
#define SCN_CD_KP_MEM_RECALL 0xd1U
#define SCN_CD_KP_MEM_CLR 0xd2U
#define SCN_CD_KP_MEM_ADD 0xd3U
#define SCN_CD_KP_MEM_SUB 0xd4U
#define SCN_CD_KP_MEM_MULT 0xd5U
#define SCN_CD_KP_MEM_DIV 0xd6U
#define SCN_CD_KP_PLUS_MINUS 0xd7U
#define SCN_CD_KP_CLR 0xd8U
#define SCN_CD_KP_CLR_ENT 0xd9U
#define SCN_CD_KP_BIN 0xdaU
#define SCN_CD_KP_OCT 0xdbU
#define SCN_CD_KP_DEC 0xdcU
#define SCN_CD_KP_HEX 0xddU
#define SCN_CD_RESERVED12 0xdeU
#define SCN_CD_RESERVED13 0xdfU
#define SCN_CD_LCTRL 0xe0U
#define SCN_CD_LSHIFT 0xe1U
#define SCN_CD_LALT 0xe2U
#define SCN_CD_LGUI 0xe3U
#define SCN_CD_RCTRL 0xe4U
#define SCN_CD_RSHIFT 0xe5U
#define SCN_CD_RALT 0xe6U
#define SCN_CD_RGUI 0xe7U
#define SCN_CD_RESERVED14 0xe8U
#define SCN_CD_RESERVED15 0xe9U
#define SCN_CD_RESERVED16 0xeaU
#define SCN_CD_RESERVED17 0xebU
#define SCN_CD_RESERVED18 0xecU
#define SCN_CD_RESERVED19 0xedU
#define SCN_CD_RESERVED20 0xeeU
#define SCN_CD_RESERVED21 0xefU
#define SCN_CD_RESERVED22 0xf0U
#define SCN_CD_RESERVED23 0xf1U
#define SCN_CD_RESERVED24 0xf2U
#define SCN_CD_RESERVED25 0xf3U
#define SCN_CD_RESERVED26 0xf4U
#define SCN_CD_RESERVED27 0xf5U
#define SCN_CD_RESERVED28 0xf6U
#define SCN_CD_RESERVED29 0xf7U
#define SCN_CD_RESERVED30 0xf8U
#define SCN_CD_RESERVED31 0xf9U
#define SCN_CD_RESERVED32 0xfaU
#define SCN_CD_RESERVED33 0xfbU
#define SCN_CD_RESERVED34 0xfcU
#define SCN_CD_RESERVED35 0xfdU
#define SCN_CD_RESERVED36 0xfeU
#define SCN_CD_RESERVED37 0xffU

#endif